### ISSUE TITLE
BH kicks are not reduced if Muller Mandel mass loss is assumed

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#1094] opened 2024-04-18 09:36 UTC
**Describe the bug**
When using the default remnant mass prescription (MULLERMANDEL) in conjunction with a non-default kick prescription (e.g MAXWELLIAN), black hole kicks are not proportionally reduced. This is because the fallback fraction is not currently defined in the MULLERMANDEL scheme, so it takes on the default value of 0. 

I would think that there should be a straightforward way to correct for this in the MULLERMANDEL prescription, e.g using the pre and post-SN masses and a nominal PNS mass of 1.4, though there may be better alternatives. 

In lieu of this fix, this restriction should be mentioned in the help page, that the --black-hole-kicks option only works if the remnant mass prescription is not MULLERMANDEL.

**Label the issue**
`urgency_moderate` - This is a moderately urgent issue
`severity_minor`    - This is a minor bug with minimal impact

**Versioning (please complete the following information):**
 - COMPAS v02.43.00

**Comment by ilyamandel** [comment] 2024-04-18 10:47
Good point, @reinhold-willcox !  I'd prefer to go for your second option: update documentation to clarify that the MULLERMANDEL remnant mass prescription is meant to go with the corresponding kick prescription.  The two prescriptions were developed jointly, and it doesn't make very much sense to me to decouple them.  Would that be OK with you?  If so, very happy to make the documentation change, which I agree is needed.

**Comment by reinhold-willcox** [comment] 2024-04-23 09:58
@ilyamandel That fix is fine with me. However, I've just come out of a meeting with my bachelor's students where we discovered that the BH kicks are also not working properly when the remnant mass prescription is Fryer12. So I think there's some deeper bug that we need to dive into. But once that's sorted, I'm happy with just a documentation flag for MullerMandel.

**Comment by ilyamandel** [comment] 2024-04-23 10:13
Can you say more about the BH kicks?  Maybe an example of where they don't work as intended?

**Comment by ilyamandel** [comment] 2024-05-05 22:58
The documentation issue is addressed in #1108 .  @reinhold-willcox , I think the Fryer12 issue you mention belongs in a different PR (it doesn't match the title of this one); please open a PR with a specific, reproducible problem description for that, since "not working properly" is very hard to track down.  Closing this issue.

**Closed as completed by ilyamandel** 2024-05-05 22:58 UTC

**Comment by reinhold-willcox** [comment] 2024-05-08 07:13
Sorry for the slow reply. I had to dig a bit deeper to see if this was a problem with compas or with my tests. I ultimately found out it was my tests that are wrong, the kicks are indeed working as intended. Since the documentation fix was addressed above, I'm happy for this to be closed.
