### ISSUE TITLE
Odd system: low mass, low Z single star experiences SESN

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#786] opened 2022-04-18 07:42 UTC
**Describe the bug**
The following grid and options produce a non-interacting binary at Z=1e-4 with a 6 Msun primary that experiences a stripped-envelope, electron capture supernova. Especially weird is that it moves off the TPAGB to become an ONeWD before undergoing SN.

Here is the detailed evolution plotting output text:
```
Time (Myr), Event,                            M1 (M_o), type1, M2 (M_o), type2, a (R_o),   e
  0.000000   Zero-age main-sequence, metallicity Z=0.0001    6.035     1      1.000     1   215032.029  0.000
 60.720839   Star 1: MS->HG                     6.035     2      1.000     1   215046.817  0.000
 60.992815   Star 1: HG->CHeB                   6.034     4      1.000     1   215066.313  0.000
 67.896165   Star 1: CHeB->EAGB                 6.004     5      1.000     1   215968.367  0.000
 68.171485   Star 1: EAGB->TPAGB                5.978     6      1.000     1   216788.255  0.000
 68.957795   Star 1: TPAGB->ONeWD               1.381    12      1.000     1   639997.158  0.000
 68.957795   Star 1 undergoes supernova and forms a NS    1.260    13      1.000     1   639997.158  0.000
5918.977976   Star 2: MS->HG                     1.260    13      1.000     2   -445.995  1362.242
5951.861187   Star 2: HG->FGB                    1.260    13      1.000     3   -446.049  1362.242
6153.808745   Star 2: FGB->CHeB                  1.260    13      0.880     4   -470.994  1362.242
6255.652949   Star 2: CHeB->EAGB                 1.260    13      0.860     5   -475.432  1362.242
6260.951375   Star 2: EAGB->TPAGB                1.260    13      0.827     6   -483.097  1362.242
6262.546375   Star 2: TPAGB->COWD                1.260    13      0.607    11   -540.058  1362.242
13863.546375   Double compact object (NS+COWD) merging in nan Myr    1.260    13      0.607    11   -540.058  1362.242
```
And the detailed plot:
![low_mass_single_sesn](https://user-images.githubusercontent.com/33348824/163773998-0823b46a-755c-49d1-ac30-681a0fab1f35.png)

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
grid.txt: `--initial-mass-1 6.034999559745024 --initial-mass-2 1.0 -a 1000`
`COMPAS --grid grid.txt --detailed --random-seed 300 --metallicity 0.0001`

**Expected behavior**
Is this just an oddity of the very low metallicity regime? Other stars at this Z with similar masses did not experience this...

**Versioning (please complete the following information):**
 - COMPAS v02.27.08

**Comment by jeffriley** [comment] 2022-04-18 08:47
> Especially weird is that it moves off the TPAGB to become an ONeWD before undergoing SN.

Is that what's described in Hurley+2000, p15, second-last paragraph (last full paragraph) left column?

> Double compact object (NS+COWD) merging in nan Myr 

Where's the 'nan' coming from?

**Comment by reinhold-willcox** [comment] 2022-04-19 01:10
Follow up on this: it appears this may be the correct behavior (in the sense that it follows the Hurley prescriptions, not that it's necessarily correct physically). But I will look into the mass range of ECSNe for single stars from all metallicites and update when I have that.

**Comment by ilyamandel** [comment] 2022-05-16 05:03
> Where's the 'nan' coming from?

This binary has been disrupted by the SN, but we don't record that correctly in detailed_evol_plotter.  That's a separate issue, though, for which I created a new issue, #801 .  @reinhold-willcox , can I close this issue, since the C++ code is behaving as intended?

**Closed as completed** 2022-05-16 11:35 UTC
