### ISSUE TITLE
COMPAS hangs on some systems. 

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#439] opened 2020-11-10 02:57 UTC
**Describe the bug**
On some specific initial conditions, COMPAS will completely hang. Cause is unknown, but it seems to occur for massive binaries with short separations, so I would guess that these are systems in contact at ZAMS. When it happens, COMPAS does not continue evolving binaries. 

**Label the issue**
`urgency_high`     - This is a very urgent issue and should be resolved as soon as possible
`severity_major`    - This is a severe bug

**To Reproduce**
Run: `./COMPAS --initial-mass-1 9.32943617585786 --semi-major-axis 0.03341866534357877 --initial-mass-2 8.366832044672574 --metallicity 0.0142 --eccentricity 0`

**Expected behavior**
Not to hang. If it is related to contact binaries, these should probably be discarded. 

**Versioning (please complete the following information):**
 - COMPAS v02.16.03

**Comment by jeffriley** [comment] 2020-11-10 04:02
The problem is that the supplied initial conditions cause RLOF at birth, but allow-rlof-at-birth option default is fals - so the BaseBinaryStar constructor loops sampling new initial conditions, and since the use supplied all the initial conditions nothing is sampled so the error condition persists and we loop forever.  Will push a fix.

**Comment by jeffriley** [comment] 2020-11-12 20:20
Fixed in v02.17.00

**Closed as completed by jeffriley** 2020-11-12 20:20 UTC
Labels: bug, severity_major, urgency_high
