### ISSUE TITLE
[h5copy.py] Dataset count mismatch between source and destination for group ....

### ISSUE THREAD

**Issue by HeloiseS** [TeamCOMPAS/COMPAS#698] opened 2021-11-15 23:16 UTC
_This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)_

I'm trying to combine two datasets of 10,000 systems each (the only difference is the metallicity) and I get an error I can't really diagnose from `h5copy.py`. Here is what I run and the trace. 

```
fste075@kvin:~/Documents/reviews/COMPAS$ python h5copy.py . -r
Processing directory /home/fste075/Documents/reviews/COMPAS
Processing directory /home/fste075/Documents/reviews/COMPAS/COMPAS_Output_1
Copying file /home/fste075/Documents/reviews/COMPAS/COMPAS_Output_1/COMPAS_Output.h5
Processing directory /home/fste075/Documents/reviews/COMPAS/COMPAS_Output
Copying file /home/fste075/Documents/reviews/COMPAS/COMPAS_Output/COMPAS_Output.h5
Dataset count mismatch between source and destination for group BSE_Double_Compact_Objects in files /home/fste075/Documents/reviews/COMPAS/COMPAS_Output/COMPAS_Output.h5 and /home/fste075/Documents/reviews/COMPAS/h5out.h5
WARNING: Group BSE_Double_Compact_Objects from file /home/fste075/Documents/reviews/COMPAS/COMPAS_Output/COMPAS_Output.h5 not copied to /home/fste075/Documents/reviews/COMPAS/h5out.h5
Dataset count mismatch between source and destination for group BSE_System_Parameters in files /home/fste075/Documents/reviews/COMPAS/COMPAS_Output/COMPAS_Output.h5 and /home/fste075/Documents/reviews/COMPAS/h5out.h5
WARNING: Group BSE_System_Parameters from file /home/fste075/Documents/reviews/COMPAS/COMPAS_Output/COMPAS_Output.h5 not copied to /home/fste075/Documents/reviews/COMPAS/h5out.h5
^CTraceback (most recent call last):
  File "h5copy.py", line 634, in <module>
    main()   
  File "h5copy.py", line 610, in main
    ok = processDirectory(thisFullPath, 
  File "h5copy.py", line 498, in processDirectory
    processDirectory(absDirpath + '/' + dirname, 
  File "h5copy.py", line 484, in processDirectory
    ok = copyHDF5File(absDirpath + '/' + filename, 
  File "h5copy.py", line 381, in copyHDF5File
    srcDataset       = srcGroup[srcDatasetName]                                                 # source dataset
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/fste075/.local/lib/python3.8/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
  File "<frozen importlib._bootstrap>", line 389, in parent
KeyboardInterrupt

```
The keybooard interupt is because after this my computer proceeds to have a bit of a stroke :) 
I get hundreds of messages like the ones below. Maybe it'd be a good idea to limit how many of these messages can pop up on the terminal? The first time I keyboard interrupted after maybe 15 seconds and couldn't scroll back up to the top of the Traceback ^^"
```
Error accessing group Age(1) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Age(2) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Ang_Momentum(1) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Ang_Momentum(2) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Ang_Momentum_Total in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Dominant_Mass_Loss_Rate(1) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Dominant_Mass_Loss_Rate(2) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Eccentricity in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Energy_Total in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Luminosity(1) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
Error accessing group Luminosity(2) in file /home/fste075/Documents/reviews/COMPAS/h5out.h5 : 'Dataset' object has no attribute 'keys'
```

**Comment by jeffriley** [comment] 2021-11-16 01:59
@HeloiseS Can you upload the two HDF5 files somewhere that I can grab them?

**Comment by jeffriley** [comment] 2021-11-16 20:13
@HeloiseS Thanks for providing the hdf5 files.  I took a look at them with h5view.py:

    $ python3 /compas/dev/my_fork/compas/postProcessing/Folders/H5/PythonScripts/h5view.py ./COMPAS_Output_Heloise_1.h5
    
    
    Summary of HDF5 file /d/compas/heloise/COMPAS_Output_Heloise_1.h5
    =================================================================
    
    File size    : 0.1149 GB
    Last modified: 2021-11-17 06:53:11.033530
    
    COMPAS Filename              Columns   Entries   Unique SEEDs
    --------------------------   -------   -------   ------------
    Run_Details                      360         1
    BSE_Common_Envelopes              73      4660           4457
    BSE_Double_Compact_Objects        12        77             77
    BSE_RLOF                          33     24910           5525
    BSE_Supernovae                    32      4270           4107
    BSE_System_Parameters             29     10000          10000
    
    
    $ python3 /compas/dev/my_fork/compas/postProcessing/Folders/H5/PythonScripts/h5view.py ./COMPAS_Output_Heloise_2.h5
    
    
    Summary of HDF5 file /d/compas/heloise/COMPAS_Output_Heloise_2.h5
    =================================================================
    
    File size    : 0.1201 GB
    Last modified: 2021-11-17 06:54:59.209393
    
    COMPAS Filename              Columns   Entries   Unique SEEDs
    --------------------------   -------   -------   ------------
    Run_Details                      360         1
    BSE_Common_Envelopes              73      3314           3217
    BSE_Double_Compact_Objects        18        65             65
    BSE_RLOF                          33     21697           5365
    BSE_Supernovae                    32      7494           7327
    BSE_System_Parameters             32     10000          10000

You can see that the number of columns (datasets for HDF5 files) differs for both BSE_Double_Compact_Objects and BSE_System_Parameters.  h5copy.py won't copy groups (BSE_Double_Compact_Objects is a group in HDF5 nomenclature) to a file that has a different number of datasets for that group.  There are reasons for that - if we're copying to an existing file (which we will be at some stage when we're joining multiple of files), and that existing file has fewer datasets in a group (aka columns in a file) than the file being copied to it, there is no place to put the new datasets (columns), and even if we create them in the existing file on-the-fly, how would we populate them for the existing file?  Similarly, if the existing file has datasets in a group (columns in a file) that the file being copied to it doesn't have, what values should be given the the dataset values missind from the file being copied?  So we just issue a warning and don't copy those groups...

This behaviour is documented in the online documentation (under the heading "Appending data":

https://compas.readthedocs.io/en/latest/pages/User%20guide/Post-processing/post-processing-h5copy.html

Did you create the files?  If so, did you use a logfile-definitions file to change what was written to the output files?

Edit: Yes, I see you did for one of the files - logfile-definitions file "/home/fste075/Documents/reviews/COMPAS/COMPAS_Output_Definitions.txt"

**Comment by jeffriley** [comment] 2021-11-16 21:58
Having said that (^^^) though, you should only see that message once per group in any affected HDF5 - so in your case you should have only seen the error twice for the second file.

And... I just re-read the issue - you're getting lots of errors about missing keys.  Let me look into that - I suspect it's a ricochet from t he mismatch problem (but it shouldn't be...).

**Comment by jeffriley** [comment] 2021-11-16 22:29
Ok, this is what I get when I do the copy:

    $ python3 /compas/postProcessing/Folders/H5/PythonScripts/h5copy.py ./files
    Processing directory /d/compas/heloise/files
    Copying file /d/compas/heloise/files/COMPAS_Output_Heloise_1.h5
    Copying file /d/compas/heloise/files/COMPAS_Output_Heloise_2.h5
    Dataset count mismatch between source and destination for group BSE_Double_Compact_Objects in files /d/compas/heloise/files/COMPAS_Output_Heloise_2.h5 and /d/compas/heloise/h5out.h5
    WARNING: Group BSE_Double_Compact_Objects from file /d/compas/heloise/files/COMPAS_Output_Heloise_2.h5 not copied to /d/compas/heloise/h5out.h5
    Dataset count mismatch between source and destination for group BSE_System_Parameters in files /d/compas/heloise/files/COMPAS_Output_Heloise_2.h5 and /d/compas/heloise/h5out.h5
    WARNING: Group BSE_System_Parameters from file /d/compas/heloise/files/COMPAS_Output_Heloise_2.h5 not copied to /d/compas/heloise/h5out.h5

It doesn't matter what order I do the copy - same result.  Can you try to reproduce and let me know if you can.  Are the files you provided the exact files you tried to join with h5copy.py?  I guess they are - maybe your version of h5py is different?  Can you try updating h5py?  And you're using python3, right?

**Comment by HeloiseS** [comment] 2021-11-17 04:01
I pulled the repo and i still get the same issue :/ weird

**Comment by HeloiseS** [comment] 2021-11-17 04:03
Also - I'm guessing i can't ensure that the BSE_Compact_objects entries will be the same number when I do two separate runs... so how can i put together my hdf5 files from two different metallicities?

**Comment by HeloiseS** [comment] 2021-11-17 04:13
well silly me - i should have done h5view.py from the start... It's because I've got a detailed output and I forgot :eyes: I have thousands of files such as `COMPAS_Output/Detailed_Output/BSE_Detailed_Output_4625.h5` - I should have known when it took 1200 seconds to run my simulation when ilya said it'd take 2 minutes... I just though kvn was slow!!

**Comment by ilyamandel** [comment] 2021-11-30 13:04
@jeffriley , @HeloiseS -- was there anything left to do with this issue?  If not, may I close it?

**Comment by jeffriley** [comment] 2021-11-30 23:09
> was there anything left to do with this issue? If not, may I close it?

Maybe :-)  When I wrote H5copy I wrote it with the COMPAS_Output.h5 files in mind - I didn't provide functionality to combine COMPAS detailed output files.  I suppose there could be a use case to combine many detailed output files into a single file, but I think it would be rarely-used functionality.  The fact that H5copy does not have functionality to combine detailed output files, and that Heloise had detailed output files in the directory tree is what caused some of the error messages described above.

At a minimum I should probably document that H5copy does not copy detailed output files, and that no such files should be in the directory tree that H5copy will traverse to find files to copy.  I could also look at putting a check in the code and emitting a clearer error message.  If anybody thinks it's worthwhile, they could open an issue to add the functionality to H5copy.

EDIT: or maybe I could check for detailed output files and just ignore them.  Actually, check for any HDF5 files that are not clearly recognisable as COMPAS_Output files and ignore anything that is not a COMPAS_Output file.

**Comment by ilyamandel** [comment] 2021-12-05 12:11
@jeffriley I agree that we should not be combining detailed output files, and should just document that.  Since I had #721 open, I just added a slight documentation tweak to it, namely, the H5 copy page now says:

This program copies ``COMPAS_Output.h5`` ``HDF5`` file(s) [but not ``Detailed_Ouput`` files] to a designated output ``HDF5`` file.

I am closing this issue.

**Closed as completed by ilyamandel** 2021-12-05 12:11 UTC
