### ISSUE TITLE
NS accretes no mass during RLOF

### ISSUE THREAD

**Issue by debatric** [TeamCOMPAS/COMPAS#172] opened 2020-03-29 09:15 UTC
NS accretes no mass during RLOF. The MassTransferTracker is updating the correct number, but since the NS is not accreting anything, it's mass is unchanged and the pulsar evolves as in isolated case. Was not the case in legacy COMPAS (DEMINK prescription of legacy being equivalent of HURLEY in Beta version).

**Comment by ilyamandel** [comment] 2020-08-06 07:28
I can confirm that NSs can and do accrete mass with the latest code version, so if there was a bug, it got fixed.  [I could not test with @debatric 's pythonSubmit because it is no longer compatible with the new code.]  E.g. the red line on the plot below represents the mass of an NS, which accretes at around 2 Gyr once its low-mass companion overflows its Roche lobe.  I am therefore closing this issue as resolved.

![NSaccretion](https://user-images.githubusercontent.com/512213/89503640-2a597600-d80a-11ea-92eb-4a8fac69b459.png)

**Closed by ilyamandel** 2020-08-06 07:28 UTC
Labels: bug
