### ISSUE TITLE
change pre-factor in thermal (kelvin-helmholtz) timescale calculation 

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#570] opened 2021-05-24 14:45 UTC
**Is your feature request related to a problem? Please describe.**
The function `CalculateThermalTimescale` uses a pre-factor of GMsun^2 / Rsun Lsun = 30.0 Myr, but when you calculate this it should actually be 31.4 Myr (see attachment) so why not update this? I also updated the documentation

**Describe the solution you'd like**
I am changing the 30.0 to 31.4 Myr. Since both numbers have the same precision , and hence the same computational cost, I do not see a (big) problem. 

<img width="528" alt="Screen Shot 2021-05-24 at 10 43 29 AM" src="https://user-images.githubusercontent.com/25804496/119364442-e80c0300-bc7c-11eb-862e-7b0b1c9d1ccc.png">

**Comment by ilyamandel** [comment] 2021-05-24 23:48
@FloorBroekgaarden -- I am not convinced we need to make this change, since the kH timescale is approximate, anyway.  It will only make the results very slightly different from previous runs (i.e., makes regression testing slightly more challenging, but otherwise little impact). That said, I also don't mind if we do this -- no harm, either.

**Comment by FloorBroekgaarden** [comment] 2021-05-25 01:09
that is correct. This change is definitely strictly not needed (the factor 30 -> 31.4) but I did not see harm in changing it? @ilyamandel , hence why I thought to update it. "Code cleanup is for the added documentation"

**Comment by ilyamandel** [comment] 2021-10-11 07:16
Addressed by @jeffriley in #646 , closing.

**Closed as completed by ilyamandel** 2021-10-11 07:16 UTC
Labels: code cleanup/optimisation
