### ISSUE TITLE
BSE_RLOF output skips a stellar type

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#604] opened 2021-08-05 03:46 UTC
**Describe the bug**
In some (rare) cases, the `BSE_RLOF` output shows a donor star with previous stellar type 1 (MS) become stellar type 7 (HeMS). This generally should not happen, since MS stars do not yet have He cores. Upon closer inspection of the detailed output, the donor is in fact a HG star for a few timesteps before it becomes a HeMS star, but this is not correctly reflected in the `BSE_RLOF` output. 

The attached screenshot shows a zoom in of the detailed evolution around the transition, and in particular that the HG phase is indeed reached. 

**Label the issue**
`urgency_low`      - This issue is not urgent
`severity_minor`    - This is a minor bug with minimal impact

**To Reproduce**
```
COMPAS -n1 --random-seed 142952 --initial-mass-1 20.572500791714123 --semi-major-axis 0.15567910245419636 --initial-mass-2 11.78490823947635 --metallicity 0.0142 --eccentricity 0
```
Edit: added `-n1` 

**Expected behavior**
The RLOF output should only ever show a MS star become a MS star. If it evolves into a HG in the middle of an otherwise typical Case A MT phase, the next line in the output should show the star as HG before stripping into a HeMS star. This seems like an issue in how the RLOF parameters are stored.

**Screenshots**
![rlof_skips_HG](https://user-images.githubusercontent.com/33348824/128287242-ff43cf4b-79b1-44cb-ada7-29c16f725c7c.png)

**Versioning (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - COMPAS v02.21.00

**Comment by jeffriley** [comment] 2021-08-05 04:10
I don't know what the goal of the RLOF printing function is.  I'm happy to help resolve the problem, but I don't know what I'm looking for.  Can someone document here what the goal of the RLOF printing function is, and what the expected output is (and when it is expected)?

**Comment by reinhold-willcox** [comment] 2021-08-05 04:20
I'm not sure I completely understand your question, but from what I remember when Coen was writing the function originally, there was a question as to when to start and stop the recording. For Case A, because it's slow and occurs over many timesteps (often stopping and restarting), there was a desire to only record the state of the system just at the beginning and end of an ongoing MT event (and save space by skipping all the interim timesteps). 

That is, I imagine, what is happening here. It starts as standard Case A, and at some point during the MT, the star evolves off the MS and becomes HG. In practice there is probably some sort of smooth transition to early Case B, but for Compas purposes, once the donor is a HG, the remnant should immediately become a HeMS star. 

For the sake of clarity of which type of MT is occurring, I suggest we add in a stop and restart if the donor type changes, such that the Case A MT ends at the last timestep where the donor is type 1, and Case B starts at the next timestep (even if the MT never really stopped). I would also propose adding in such a stop and restart if the accretor changes type, in case we want to compare different MT events based on the accretor (e.g Case BB onto a standard object which then becomes a compact object).

**Comment by jeffriley** [comment] 2021-08-05 04:35
When I refactored the COMPAS code, I rewrote Coen's RLOF printing code - but in doing that all I did was reproduce the functionality as it was.  So I know how it works, but I don't know how it is supposed to work - unless the code does exactly what it is supposed to do, in which case knowing how it works means I know how it is supposed to work.  I can't find where it is not working correctly unless I know what it is supposed to do.

So, what's the goal of RLOF printing?  What are you expecting to see in each record in the BSE_RLOF file, and when should a record be written?

What is supposed to be recorded, when is it supposed to be recorded, and why?

ps. It sounds like you know more about how it is supposed to work than I do - feel free to fix it however you think it should be fixed...

**Comment by reinhold-willcox** [comment] 2021-08-05 05:04
My preferred functionality is to print RLOF output only when RLOF starts and stops (as it currently does), and _also_ when the stellar type of either star changes (which it does not currently do). I'm not sure how to implement that, but I'll take a look.

**Comment by jeffriley** [comment] 2021-08-05 05:07
Ok, look at BaseBinaryStar::StashRLOFProperties() - it keeps a "previous" and "current" version of the RLOF properties, including the stellar type of both stars, so you should be able to determine if either (or both) of the stars changed stellar type.

**Comment by jeffriley** [comment] 2021-08-10 21:57
@reinhold-willcox @themikelau 

> My preferred functionality is to print RLOF output only when RLOF starts and stops (as it currently does)

What does "only when RLOF starts and stops" mean in this context?  Reinhold notes "(as it currently does)" - looking at the code, I see

BaseBinaryStar::PrintRLOFParameters() is called from BaseBinaryStar::Evolve() at every timestep (the same frequency as BaseBinaryStar::PrintDetailedOutput())

BaseBinaryStar::PrintRLOFParameters() performs two checks:

(a) it checks that RLOF printing is enabled - if it is not, the function does nothing
(b) it checks if at least one of the stars is experiencing RLOF, and if not, does nothing

So, if RLOF printing is enabled, and at least one of the stars is in RLOF, BaseBinaryStar::PrintRLOFParameters() prints a record to the BSE_RLOF log file.

I don't understand how "only when RLOF starts and stops" works - I must be either missing something in the code, or misunderstanding what "only when RLOF starts and stops" means.  Once I understand exactly what's required, I can probably make it work the way you want.

So, it looks to me that BaseBinaryStar::PrintRLOFParameters() should print at every timestep as long as at least one of the stars is in RLOF, so it shouldn't miss a stellar type switch if the switch happens while one of the stars is in RLOF.  If the switch happens while neither star is in RLOF, then we wouldn't print a record to BSE_RLOF anyway (because neither star is in RLOF).

One thing to note is that while BaseBinaryStar::PrintRLOFParameters() and BaseBinaryStar::PrintDetailedOutput() are being called with the same frequency, there is a call to EvaluateBinary(dt) between them (after the call to BaseBinaryStar::PrintDetailedOutput() and before the call to BaseBinaryStar::PrintRLOFParameters()), which could explain why the stellar type switch is recorded in the detailed output file but not the RLOF file.

If you can give me a pythonSubmit file that shows the problem for a single binary (so that I can turn detailed output on), I'm happy to take a further look.

**Comment by jeffriley** [comment] 2021-08-10 23:31
Oh, forgot to add

> and also when the stellar type of either star changes

You might need to look at the switchlog functionality for that - it may even be that just using switchlog is enough for you (especially if you add columns to the switchlog file - talk to @ilyamandel - he uses the switchlog functionality)

**Comment by reinhold-willcox** [comment] 2021-08-11 04:56
Sorry, I was mistaken in some of my previous posts. What it currently does is to output RLOF details every time RLOF is occurring. Not at the start and stop points like I said above. That was a functionality I discussed with Coen ages ago, that I thought was implemented (and which I thought I was seeing in the output). Caveat: the idea was that Case A MT often occurs over many timesteps, so we could save on output lines if we only print when it turns on and turns off, but that's not what is happening here. 

However, it's not quite right that PrintRLOFParameters and PrintDetailedOutput are called with the same frequency. It is called once during the primary while loop for each timestep, in BaseBinaryStar::Evolve(), just before the EvaluateBinary(dt) and PrintRLOFParameters(), but it is called again in the EvaluateBinary(dt) function, if the flag m_PrintExtraDetailedOutput is set at any point during the evolution. This flag is possibly set a number of times, but as best I can see, it is set every time the stellar type of either star changes. If the flag is set, PrintDetailedOutput is called after all of the binary interactions have been calculated, but before the binary properties (e, a, E, J) and/or supernova are evaluated. 

From memory, this extra detailed printing was put in so that in the detailed output files, we would see the stellar type changes occur "instantaneously", and would be plotted as a vertical line in the plotting script. But this could potentially be the source of the problem. Here is what I think is happening: For the problematic event listed at the top, we start the timestep as a MS star in Case A onto another MS. It transitions into a HG star from just the SSE component, and the detailed output records it as a HG star with a MS companion. Then during BSE, the MT donor is correctly identified as a HG star, so it's (brand new) envelope is completely removed and we are left with a HeMS star. So at the beginning of the timestep, it is MS, and by the end it is HeMS. This is what is shown in BSE_RLOF. And it is a natural consequence of evaluating both SSE and BSE in the same timestep. 

My previous suggestion to evolve only SSE or BSE in any given timestep is probably too drastic, but maybe we could clean up the RLOF printing issue if we stashed the RLOF parameters more cleverly. Potentially, we should stash them after the SSE component, and then call the printing function after the BSE component, instead of stashing and calling at the same time after BSE. What do you think @jeffriley ?

**Comment by jeffriley** [comment] 2021-08-11 05:55
> but it is called again in the EvaluateBinary(dt) function, if the flag m_PrintExtraDetailedOutput is set at any point during the evolution

That is true - I'd forgotten about that (actually I thought at one stage you took that code out - maybe I was dreaming).  I think we should change that (more below).

> Potentially, we should stash them after the SSE component, and then call the printing function after the BSE component, instead of stashing and calling at the same time after BSE.

Do you mean stash them in the SSE code, and print from the BSE code?  That's problematic.  Or do you mean stashing the RLOF details after calling BaseBinaryStar::EvolveOneTimestep(), and printing them sometime later?

I think we could do this by using the mechanism that I put in place for the switchlog functionality.  I think we should look at changing the detailed output code so that we remove the m_PrintExtraDetailedOutput flag and instead call PrintDetailedOutput() whenever a stellar switch happens - I need to think about that a bit more.  We should be able to use the same mechanism to print the RLOF details whenever a stellar switch occurs.  The way the detailed output and the m_PrintExtraDetailedOutput  flag works at the moment, we have to check at various points in the code to see if a stellar switch occurred - with the switchlog mechanism we are told when it occurs and can react immediately.  

Let's talk about exactly what it is you need - maybe we can Zoom in the next day or two and chat.

**Comment by jeffriley** [comment] 2021-08-11 08:18
Btw, just to be clear:

> It transitions into a HG star from just the SSE component

Stars only ever switch stellar type in what you refer to as the SSE component.  Only the BaseStar class and stellar types classes (CHeB, HeMS, HeHG.cpp etc.) operate directly on single stars - the binary star class does not operate on single stars (so a star will never switch type in the BaseBinaryStar class for example - the stellar object (either the primary or the secondary star) may be told to evolve from the BaseBinaryStar class, but what happens during that evolution happens in the stellar classes.

**Closed as completed** 2021-08-22 05:01 UTC
Labels: severity_minor, urgency_low
