### ISSUE TITLE
Allow user to disable detailed output for SSE mode 

### ISSUE THREAD

**Issue by SimonStevenson** [TeamCOMPAS/COMPAS#403] opened 2020-10-16 07:53 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, when running with single-star=True you will always get detailed output. The code should respond to the --detailedOutput flag i.e. if this is not provided (or set to False in the python submit) then detailed output files should not be generated. This would allow the user to e.g. generate a population of single supernovae without a large number of detailed output files building up (my use case, there are probably other use cases). This would also go towards making the SSE and BSE modes behave similarly.

**Describe the solution you'd like**
Make code respond to --detailedOutput flag when using --single-star

**Describe alternatives you've considered**
No change. 

**Additional context**
Towards making SSE and BSE modes more similar.

**Comment by jeffriley** [comment] 2020-10-17 08:30
Duplicate of issue #361 

I am happy to resolve #361 - I know I haven't got to it yet, but I plan to...

**Comment by SimonStevenson** [comment] 2020-10-17 10:47
Ah woops sorry I forgot about the other issue, I should have looked first. Just hit this again and wanted to make sure it was on the to do list. Happy to close this issue and just use 361

**Comment by ilyamandel** [comment] 2020-10-17 11:05
Closing this one, keeping #361 .

**Closed as completed by ilyamandel** 2020-10-17 11:05 UTC
Labels: enhancement, urgency_low
