### ISSUE TITLE
Slow performance compared to older versions

### ISSUE THREAD

**Issue by dumbscholar** [TeamCOMPAS/COMPAS#1246] opened 2024-10-19 02:25 UTC
Since v3.00.00 I see a strange performance issue. If I give 5 or 6 parallel runs of COMPAS with the same arguments (varying only metallicity), I find that some runs finish in 5-6 hours, while others take up to 12.5 hours.

In earlier versions, I could give up to 8 parallel runs (with the same command as used for later versions) and all would complete in under 3 hours. I have sufficient memory and storage as I suppress the creation of most of the spacious log files.

Also, the run (for a given metallicity) pauses very briefly at certain times (perhaps it encounters some floating point errors). In earlier versions it went smooth throughout.

I use the following command. I only vary the metallicity and output container values across runs.

--mode 'BSE' --initial-mass-min 5.0 --eccentricity-distribution 'THERMAL' --number-of-systems 1000000 --switch-log False --detailed-output False --logfile-type 'CSV' --allow-rlof-at-birth False --logfile-supernovae '' --logfile-common-envelopes '' --logfile-rlof-parameters '' --metallicity 0.0105 --random-seed 0 --output-container Z.0105

Version (last checked):

COMPAS: 3.05.02

Likely cause:

Elaborate error handling scheme

OS: MacOS
Memory: 18GB
Storage: >100GB free

**Comment by jeffriley** [comment] 2024-10-19 07:55
I can't rule it out until I look, but any performance degradation as a result of the changes in v03.00.00 is unlikely to be the new error handling functionality. There were two types of error handling added, or modified, in v03.00.00:

(1) floating-point error handling was added. This functionality is OFF by default.  Even when it is ON it has a very light touch, and
is only invoked if a floating-point error is encountered.  If a floating-point error is encountered, the fp error handling code will immediately trap and the evolution of the star, or binary, will terminate. If there were lots of fp errors this would cause the runtime to decrease rather than increase vis-a-vis earlier versions.

(2) instead of assuming a default value if unknown or invalid option values are encountered, the code was changed in v03.00.00 to immediately terminate the evolution of the star or binary in such circumstances.  Again, if this happened a lot we'd expect the runtime to decrease rather than increase.  There is negligible overhead in the change - we already had code that set a default if an unknown or invalid option values was encountered (so we were already detecting the condition) - instead of setting a default we terminate.

There was a lot of code cleanup done in v03.00.00.  A more likely cause of any performance degradation is that I made a mistake with that cleanup (or an  undocumented change snuck in).

I'll take a look at this soon,

**Comment by dumbscholar** [comment] 2024-10-19 10:20
Just a small remark:

Following are the typical runtimes with different versions (system on continuous power supply, mild other app usage):

COMPAS v03.05.02
5.0-12.0 hrs

COMPAS v03.05.00
5.5-12.0 hrs

COMPAS v03.03.00
5.5-12.0 hrs

COMPAS v03.01.09
5.5 hrs (upper limit not checked)

COMPAS v03.00.05
5.5 hrs (upper limit not checked)

COMPAS v03.00.01
4.5 hrs (upper limit not checked)

COMPAS v03.00.00
4.5 hrs (upper limit not checked)

COMPAS v02.50.01
2.5-3.0 hrs

COMPAS v02.49.05
2.5-3.0 hrs

**Comment by jeffriley** [comment] 2024-10-23 01:17
Fixed in PR #1251 

The root cause of the performance degradation was the treatment of deprecated option and values introduced in v03.00.00.  We give users a grace period between announcing deprecated options and/or option values, so users can continue to specify deprecated options and option values until the grace period is over and we remove the deprecated options and/or option values.  Because during that grace period users can specify either the deprecated option, or its replacement (if applicable - some options will just be removed, while others will be replaced with different names), we need to check which option value to retrieve.  In versions prior to this PR, we performed that check by calling the function OPTIONS->OptionSpecified() to determine which of the options was specified (the deprecated option, or the replacement).  The OPTIONS->OptionSpecified() function determines if an option was specified by traversing the list of specified options provided by Boost (Boost creates the list durng its parsing of the options).  Traversing that list doing string comparisons takes some time, and doing it every timestep for one or more deprecated options is what introduced the performance degradation (mea culpa - it just didn't occur to me at the time - I wrote the OPTIONS->OptionSpecified() function a long time ago...).

To try to resolve the problem, I wrote a new function (OPTIONS->OptionDefaulted()) which is good proxy for OPTIONS->OptionSpecified() (if an option was not defaulted, then it was specified), but only if the option name provided to OPTIONS->OptionDefaulted() is a valid option name.  It should be, since the person writing the code needs to specify it, but that can't be guaranteed (so caveat utilitor).  Determining if an option was defaulted is less onerous that determining if it was specified (by a factor of about 7), but as it turns out not enough to fix the performance degradation.  However, it is useful and I have left it in the code.

Fortunately, COMPAS parses the options provided by the user before we pass them to Boost for parsing - so that we can expand (e.g) ranges and sets, etc. (things that Boost knows nothing about).  I have now added code to the COMPAS parsing of the options to detect and replace (where necessary) deprecated options and option values.  This means that the COMPAS code beyond the initial parsing of options does not need to determine which version of the option/value was specified by the user - by that time, because we detect and replace deprecated options during the COMPAS pre-parse of options, we know that the replacement will be specified if one exists, or the deprecated option will be specified where no replacement exists, obviating the need to determine which.  This has resolved (reverted) the performance degradation.

I also changed remaining calls to OPTIONS->OptionSpecified() to OPTIONS->OptionDefaulted() - carefully checking that in each case the option string passed is a valid option.  These calls are outside the evolution loops - they are at the creation of the star or binary, so only performed once per system evolved.  Still, every little bit helps.

EDIT: I built this fix on v03.00.00, then tested v03.00.00 with the fix against v02.50.01 for runs of 100,000 binaries - the run times were virtually identical (less than a second apart).  Any increase in runtime between v02.50.01 and whatever version this fix is applied to (latest dev) will be as a result of added/changed functionality since v03.00.00.

**Closed as completed** 2024-10-25 03:05 UTC
Labels: bug, severity_moderate, urgency_moderate
