### ISSUE TITLE
Refactoring pythonSubmit.py

### ISSUE THREAD

**Issue by HeloiseS** [TeamCOMPAS/COMPAS#715] opened 2021-11-24 18:37 UTC
_This issue is submitted as part of the JOSS review [#3838](https://github.com/openjournals/joss-reviews/issues/3838)_

When it comes to the pythonSumbit.py file refactor you can go one of two routes - the one you choose will depend on whether you *ever* use the pythonProgramOption class anywhere else. 

If you do not use that class anywhere else, there it is not a use case for a class. Remove the class, just have the  giant list of options listed as it is, your comments are detailed already, and maybe instead of having two separate lists for the commands and the variable names, you can put those in a dictionary directly. You do not need a whole bunch of functions and methods (e.g. the ones whose sole purpose is to make and return the list) if they are only called one time in the __main__ portion of the file. 

If you DO want this to be a class to be imported in other scripts and feel OO is necessary, then the main thing is to remove the methods without purpose (e.g. creating lists doesn't need to be done in a method) and have an __init__ method. importantly this method would then be where you parse the configuration for COMPAS so that you don't have to go in the class everytime you want a different simulation. **if you are going to keep it a class, your user shouldn't have to modify the class itself to change the COMPAS options**, that is behaviour you expect from a script, not a class. You can put your options in a setup file in a format like yaml. This makes the actual code in pythonSubmit much shorter. Here is a quick refactor i did early on (note github won't let me have .py or .yaml so  you'll need to amend the extension after downloading) that you can use as inspiration or to build on. Note I have not tested this refactor extensively.

[compas_config.txt](https://github.com/TeamCOMPAS/COMPAS/files/7598005/compas_config.txt)
[pythonSubmitDemo.txt](https://github.com/TeamCOMPAS/COMPAS/files/7598006/pythonSubmitDemo.txt)

**Comment by reinhold-willcox** [comment] 2021-11-25 00:08
If I can add my two cents to this, since we need a major refactor of the pythonSubmit code anyway, I propose we work with the stroopwafel folks to put together a single script where users can specify all COMPAS parameters, as well as whether to use stroopwafel and/or HPC (and the related parameters there), instead of having many disparate scripts that will sometimes need to be combined in some convoluted way.

**Comment by HeloiseS** [comment] 2021-11-25 02:30
yes please - was there a stroopwafel tutorial i missed? i haven't used that yet

**Comment by reinhold-willcox** [comment] 2021-11-25 04:40
You haven't missed anything! Some of the compas people / affiliates have been working toward improving stroopwafel, and there currently exists a stroopwafel interface file for compas which is external to the compas code. But it's been on ongoing question how best to bring stroopwafel, or just the interface file, into compas.

**Comment by katiebreivik** [comment] 2021-11-25 15:59
@reinhold-willcox +++1 to your suggestion! Keeping a consistent, single interface to the c++ code is a great idea. And I agree with @HeloiseS that the options should not be baked into a class. Ideally, I think a user should be able to specify options through a command line interface or an ini/text file since modifying submit scripts introduces many opportunities for a user to break the code.

**Comment by jeffriley** [comment] 2021-11-26 20:01
Users can specify options via the COMPAS command-line interface (only those that the user wants to differ from the default values need to be specified).  All pythonSubmit sought to do was provide an .ini-like file because in the past specifying the command-line arguments was a bit cumbersome, but we've made that a lot better.  The only time I ever use pythonSubmit to run COMPAS is when somebody sends me a pythonSubmit file to reproduce a problem, otherwise I just run it from the command line.  I'm all for bringing stroopwafel into the COMPAS suite, but the core COMPAS executable should remain capable of being run standalone.

The grid file functionality effectively provides an enhanced .ini-like capability.

**Comment by avigna** [comment] 2021-11-30 11:04
@HeloiseS thank you very much for the scripts you shared: they read great and will be used to create a revised version of the python code to submit COMPAS runs. We agree with most of what you suggest, and plan to address the suggestions in a revised version of the scripts. There are two items I want to comment on:

1. Refactor to a class: currently, the stroopwaffel script uses the pythonProgramOption class. Moreover, there might be additional and alternative approaches that might benefit from a pythonProgramOption class. While we will clean the code, we currently believe that we should keep pythonProgramOption as a class and only change later if wanted or needed (post JOSS review).
2. We will use a yaml file to create parse the options. For the reivew, we will upload a file with the default options. Once the JOSS review is done, I will open an enhancement "issue" to automatically generate a yaml file with the default COMPAS options/setting, in order avoid confussion and conflicting defaults.

If you do not have any objections with this, I will work on the cleaning and get back to y'all asap. Otherwise, we can keep fine tuning.

**Comment by HeloiseS** [comment] 2021-11-30 17:44
That's cool. I asked several times where the class was used and no one mentioned strooowaffel so I wasn't aware of dependencies. 

Sounds like you've got a plan!

**Comment by ilyamandel** [comment] 2022-01-09 23:35
Since pythonSubmit has been replaced, I am closing this issue.

**Closed as completed by ilyamandel** 2022-01-09 23:35 UTC
