### ISSUE TITLE
FastCosmicIntegration maximum chirp mass error

### ISSUE THREAD

**Issue by reinhold-willcox** [TeamCOMPAS/COMPAS#817] opened 2022-06-15 14:26 UTC
**Describe the bug**
This bug was discovered by @adam-boesky who is a summer student working with Floor. 

When running the FastCosmicIntegration pipeline on a typical data file, the following error was thrown. 

```
UserWarning: Maximum chirp mass used for detectability calculation is below maximum binary chirp mass * (1+maximum redshift for detectability calculation)
```

Looking at the source code, the error comes from the following:
```
if max(chirp_masses)*(1+max_redshift_detection) < Mc_max:
        warnings.warn("Maximum chirp mass used for detectability calculation is below maximum binary chirp mass * (1+maximum redshift for detectability calculation)", stacklevel=2)
```
where Mc_max = 300 and max_redshift_distance = 1 by default. 

By inspection, the inequality looks like it should go the other way. Can someone who is more familiar with the FastCosmicIntegration confirm this? If so, the fix is easy.

**Label the issue**

`urgency_high`     - This is a very urgent issue and should be resolved as soon as possible
`severity_minor`    - This is a minor bug with minimal impact

**Versioning (please complete the following information):**
 - COMPAS v02.31.03

**Comment by jeffriley** [comment] 2022-06-15 19:38
This was already raised in issue #591 and was fixed in PR #628 

So when did we lose the fix?  Was it backed out unintentionally?  That would raise questions about other changes and fixes that we might also have lost...

**Comment by reinhold-willcox** [comment] 2022-06-15 20:13
This is a weird one...

You can see the history of commits here: https://github.com/TeamCOMPAS/COMPAS/commits/6b13662f893cfcf10eaffd7462021001d65e8c73?after=6b13662f893cfcf10eaffd7462021001d65e8c73+69&branch=6b13662f893cfcf10eaffd7462021001d65e8c73&qualified_name=6b13662f893cfcf10eaffd7462021001d65e8c73

If you run 
```
$ git checkout 5eb0bc5 
$ cd '...'/Folders/CosmicIntegration/PythonScripts/ 
$ git diff bb83bdf f707f87 FastCosmicIntegration.py | grep Mc_max
-    if max(chirp_masses)*(1+max_redshift_detection) < Mc_max:
+    if max(chirp_masses)*(1+max_redshift_detection) > Mc_max:
```
you'll see that this is where the incorrect < was swapped in back for the >, seemingly in `bb83bdf`. But that PR doesn't show any changes to the FastCosmicIntegration file.

**Comment by jeffriley** [comment] 2022-06-15 21:30
Ok, I'm not sure of the exact timeline/details (haven't looked in-depth), but PR #626  was merged on October 4, 2021, and this is what I think happened:

The fix for issue #591 (and this issue) was in commit a4a086a, but was removed in commit 4010d38, and those commits were merged in 580ae41

Until we look a bit deeper I can't tell if this was just an inadvertent thing (possibly @ilyamandel  modified an old version of FastCosmicIntegration.py for the second commit?), or whether something unexpected happened.  I'm not the git/github expert, so I'll leave it to someone else (@reinhold-willcox ?)

**Comment by jeffriley** [comment] 2022-06-15 22:28
Also, I can't see PR #626 in the list of commits.  I can access it via the link from issue #591 or from the actual PR, but I don't see it in the list of commits - the PR indicates it was merged on October 4, 2021, but I don't see it...

**Comment by reinhold-willcox** [comment] 2022-06-16 13:15
I spent a bit of time on this yesterday, but really couldn't figure it out. The fix that Ilya made is in the commit history of the dev branch. Then at a future point it's not there anymore. But there is no commit that "undid" the fix. I thought git was designed precisely to avoid this sort of thing happening, so I'm pretty baffled. It's not really a huge issue, but it would be nice to get some clarity to make sure we're not losing other changes quietly in the repo. Do you think any of the ozstar team would be willing to take a look?

**Comment by jeffriley** [comment] 2022-06-16 19:30
The ADACS people?  I don't think they are github experts - but maybe.

**Comment by jeffriley** [comment] 2022-06-17 00:48
Ok, I did some more poking around.  It looks like we have lost all changes from PR #628.

Here are some images of the diff for FastCosmicIntegration.py from PR #628 .  Comparing this to the current dev branch, it looks like we have lost all of these changes, not just the fix for the problem described i n the issue (the backwards check).

![FastCosmicIntegration py 1](https://user-images.githubusercontent.com/26860470/174200571-68245a62-a790-4f4d-971c-575e872d1ce2.png)
![FastCosmicIntegration py 2](https://user-images.githubusercontent.com/26860470/174200578-b1476211-0baa-435a-92db-0fddad7883ed.png)
![FastCosmicIntegration py 3](https://user-images.githubusercontent.com/26860470/174200580-0d656216-9325-49b3-9763-a33e840db756.png)
![FastCosmicIntegration py 4](https://user-images.githubusercontent.com/26860470/174200583-51e0b496-27fe-48ed-b99c-819867901239.png)

@ilyamandel can you check the changes you made in PR #628 against the current version of FastCosmicIntegration.py?  We probably also need to look at any other changes made in the PR to see what else we may have lost - I haven't checked anything beyond FastCosmicIntegration.py.

I still don't know why this has happened.

**Comment by jeffriley** [comment] 2022-06-17 01:21
I exported all commits on all branches to a .csv file.  I can't see PR #628 in the file - I see other PRs, but not #628.  I don't think I know enough about git/github to know why that PR is not in the file.

[gitlog.csv](https://github.com/TeamCOMPAS/COMPAS/files/8923732/gitlog.csv)

**Comment by reinhold-willcox** [comment] 2022-06-17 17:51
I agree all those changes have been lost, but they were all commited to the dev branch, so I also don't know why this happened. 

Short term, we can just reintroduce those same changes in a new PR (I can take a look at this at some point if no one else gets to it first). But long term we should definitely figure out what happened. If there are no ADACS git experts, maybe we can find one externally?

**Comment by jeffriley** [comment] 2022-06-17 20:57
These were the other changes made in PR #628.  It looks like we have lost 'generate_frame_file.py' (at least I can't see it in the repo).  I can't see getting_started.md - did we remove that?

So it looks like we lost everything done in PR #628 - was it reverted or something?  I can't see where that happened.  I still think it's odd that I can't see PR #628 in the commit history - not sure what that means.

![PR628_1](https://user-images.githubusercontent.com/26860470/174400205-8c7a667b-6449-4926-be6e-39bb7cf6d0bd.png)

![PR628_2](https://user-images.githubusercontent.com/26860470/174400209-37524368-8d5f-4f54-b247-377b2b01b14c.png)

**Comment by ilyamandel** [comment] 2022-06-17 21:39
Very interesting -- according to https://github.com/TeamCOMPAS/COMPAS/pull/628, @jeffriley merged in the commit [fd2d95c](https://github.com/TeamCOMPAS/COMPAS/commit/fd2d95cf8a42c384e23528085029982545f8a65e) -- but that commit only includes some of the changes made in PR 628.  In fact, it's just the last of the 10 commits that comprise that PR: https://github.com/TeamCOMPAS/COMPAS/pull/628/commits .  Jeff, not sure how only that sub-commit was included ...

Anyway, let me try to restore the deleted branch and resubmit the PR.

**Comment by ilyamandel** [comment] 2022-06-17 21:41
Hmmm.  Undeleted the deleted branch, but can't pull it:

$ git checkout MergerOutput
Branch 'MergerOutput' set up to track remote branch 'MergerOutput' from 'origin'.
Switched to a new branch 'MergerOutput'
MU00152639X:src ilyam$ git pull
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
error: The last gc run reported the following. Please correct the root cause
and remove .git/gc.log.
Automatic cleanup will not be performed until the file is removed.

fatal: bad object refs/remotes/origin/HEAD
error: failed to run repack

**Comment by jeffriley** [comment] 2022-06-17 22:02
>  Jeff, not sure how only that sub-commit was included

Yeah, me either - all I would have done is click on the 'Merge' button...  Strange.

**Comment by jeffriley** [comment] 2022-06-17 22:03
And... the commit that did get merged was lost...

**Comment by ilyamandel** [comment] 2022-06-26 16:45
Thanks, @reinhold-willcox -- closing.

**Closed as completed by ilyamandel** 2022-06-26 16:45 UTC

**Comment by reinhold-willcox** [comment] 2022-07-27 00:33
Recording here the larger issue and long term solution. 

The problem was that a file was modified in a branch and then merged into dev, but a new branch was spun off the original branch and the file was reverted in the new branch. When the new branch was merged into dev, the file was reverted. But because github PR diffs compare the head of the new branch to the original splitting off point, the diff on the reverted file showed no difference and it was not a "changed file" in the PR. 

The solution was to add a status check for branches undergoing PR, that they must be up to date with dev before they can be merged in. This prevents opportunity for user error.
