### ISSUE TITLE
ambiguous default header in supernova output - related to enhancement SN output.

### ISSUE THREAD

**Issue by FloorBroekgaarden** [TeamCOMPAS/COMPAS#183] opened 2020-03-31 17:12 UTC
the current supernova header (COMPAS v02.09.02) has as header names: 

'Mass_CO_Core@CO_SN', 'Mass_CP', 'Mass_Core@CO_SN'

But I think this shouldn't be @CO_SN, but just "@_SN"? 

It regards the 'Supernovae' CSV output files. (For some reason I can't add the CSV file so I attached a screenshot of the output file)

<img width="875" alt="Screen Shot 2020-03-31 at 7 12 18 PM" src="https://user-images.githubusercontent.com/25804496/78055251-8c4d2f00-7383-11ea-82cc-5353225aa57e.png">

**Comment by TeamCOMPAS** [comment] 2020-04-04 01:54
I checked the values of these variables in the output produced by Jeff for final testing, https://files.slack.com/files-pri/TLLF6Q46S-F01148DNPJ7/download/compas_output_h5_167500.tar.gz .

I see completely unphysical values for Eccentricity (up to 10^5) and Separation (negative) in some cases.  These do not match the values of Eccentricity<2ndSN and Separation<2ndSN, which at least look reasonable (though I have not checked if they are correct).  

Elevating this issue to a bug.

**Comment by ilyamandel** [comment] 2020-04-04 01:57
[Sorry, last comment was from me -- forgot that I was still logged in as TeamCOMPAS when making the repo public :) ]

**Comment by jeffriley** [comment] 2020-04-04 05:46
I don't mind raising an issue for the negative separation and large eccentricity values (though I think that is explained by the binary being unbound, and the issue is really what we should print in that circumstance), but if we elevate this issue to a defect we lose the original intent of the issue - to sort out ambiguities and confusion in the header strings.  I think the problem of negative separation and large eccentricity relating to unbound binaries should be raised as a separate isuue.

**Comment by ilyamandel** [comment] 2020-04-04 07:21
Agreed.

**Comment by reinhold-willcox** [comment] 2020-04-05 00:25
Floor, Debatri, and I were discussing best naming conventions for the different supernova parameters the other day. Here is what we came up with: [vars.txt.](https://github.com/TeamCOMPAS/COMPAS/files/4432747/vars.txt) Would be great to get feedback from others on whether they like these new parameter names, at least in the output file (if not in the code itself).

I also think the negative separations and >1 eccentricities are not a huge issue as long as the user knows that they apply to unbound systems, and they can be useful in checking that we are correctly calculating postSN orbital parameters.

**Comment by jeffriley** [comment] 2020-04-05 02:29
Ok, I think we need to have a Zoom meeting to discuss this.

One example from your document :

> massCompanion				Mass_CP,
> massRemnant				Mass_SN,

I assume what you want here are two variables in the COMPAS code named massCompanion and mass Remnant, and their headers to be "Mass_CP" and "Mass_SN" respectively?  And presumably those variable need to be in the binary star class, because only the binary knows about a remnant and companion.

The variable that records the mass for a star is BaseStar::m_Mass.  So when COMPAS prints the mass of the companion star it just prints m_Mass for the object in the code that is the companion star (that object is a variable in the binary star class that points to an object of one of the stellar classes (i.e. one of the classes that inherits ultimately from BaseStar).  Same for the remnant (the star that went SN).  The binary star does not need to track the masses of its constituent stars, and should not - they keep track of their own masses - so creating two variables (presumably in the BaseBinaryStar class) named massCompanion and massRemnant to track the masses of the constituent stars of the binary is redundant and I think would be confusing.  That's kind of defeating the purpose of OO code...

So, let's get together and talk about what problem we're trying to solve and how best to solve it.

**Comment by reinhold-willcox** [comment] 2020-04-05 03:26
Sorry, I should have been clearer. All I'm really looking for is different headers in the output file, I'm not really bothered with what compas code calls them. The vars.txt columns are `suggestedNewName     current_name` 

But I agree, we should chat about this at some point.

**Comment by jeffriley** [comment] 2020-04-05 04:01
Ok, here's my 2-cents' worth - something to think about before we get together to thrash this out.

There is a lot of confusion around what different columns and header strings mean in new COMPAS.  I think most of that stems from the fact that in new COMPAS all properties have one, and only one, associated header string – so that header string becomes the column header for that property regardless of the file it is printed in (with an appropriate suffix to indicate to which star of a binary the column refers: “_1” for the primary, “_2” for the secondary, “_SN” for the supernova, and “_CP” for the companion (“_SN” and “_CP” are used (generally) in the context of the Supernovae file).

For example, the column for the property “Mass” will have a header string of:
    “Mass” in the SSE Parameters file
    “Mass_1” or “Mass_2” in the BSE System Parameters file (for the primary and secondary)
    “Mass_SN” or “Mass_CP” in the BSE Supernovae file
and any of those in the other files depending upon context.

Note that the root header string (“Mass”) is the same – just the suffix is different.

In the example from the vars.txt file:

If we want “massCompanion” printed when we print the mass of the companion star (instead of “Mass_CP”), we could change the suffix that denotes “companion” from “_CP” to “Companion”.  Similarly, if we want “massRemnant” printed when we print the mass of the star that went supernova, we could change the suffix that means “supernova” from “_SN” to “_Remnant”.
The thing to remember is that the header strings are built from a base string (e.g. “Mass” for mass, “Radius” for radius, “Mass_Core” for core mass, “Mass_CO_Core” for Co-core mass, etc.).  So if we print the radius of the primary, we start with the base string “Radius” and add the suffix for the primary start (“_1”).  If we change the base string to something like “massRemnant”,  then whenever we print the mass we will see the header string “massRemnant”, and that won’t work for the system parameters file for example (we print the mass of both stars in separate columns -  we can’t have two columns labelled “massRemnant”).

I think what is causing some of the confusion is that in legacy COMPAS properties have different header strings associated with them depending upon which file they are printed in.  For example, the legacy Supernovae file, the column with the header string “MassStarSN” is not (as I thought it would be) the variable in the code that stores the mass of the star that went SN – it is actually the variable in the code that stores the total mass at compact object formation of the star that went SN (why do we qualify that with “total” btw?  Isn’t “mass” always the total in COMPAS?  We qualify envMass, CoreMass etc., but I thought we use “mass” to mean “total mass”).  The variable in the code that stores the mass of the star that went SN is printed under the header string “Mrem” in the Supernovae file – so I guess the record is printed after the event, and the value printed under the header string “MassStarSN” is actually the (total) mass just prior to the SN event, and “Mrem” is the mass just after the SN event.  Note that the variable that holds the mass of the star that went SN is printed under the header “mass1” (or “mass2” if it is star2) in the SystemParameters file (not “Mrem” because “Mrem” is context-dependent), so there are several header strings associated with the same variable in the code, and they are used in different contexts (for different files).

I had thought that each property should have a single, unique header string – the (e.g.) radius of the star is always the radius of the star, no matter what file we print it in, and the user should be able to interpret it based on the context of the file they are reading.  I still think that, but I can see it is causing confusion.  And as Ilya noted, the casual user doesn’t know where in the code we printed the record, so may not know the context context (but we could document that the records in the Supernovae file, for example, give the values of the properties immediately following the SN event).

The bottom-line is that I propose we change the code so that each property has a unique header string associated with it for each of the output files – that way we can have different column headers for the same property depending upon which file is it written to.  The code changes aren’t complex, but they will be a little tedious simply because we have a lot of properties that can be printed, and a little bit of work would need to be done if we ever add or remove an output file.

Under this proposal, instead of just having the header string “Mass” for the variable that holds the mass of a star, and adding an appropriate suffix when we print it, we can have something like the following:

    For the mass of a star, print the header string:

        “Mass1” and “Mass2” (or “MassPrimary” and “MassSecondary” if that’s preferable) in the SystemParameters file

    “MassSupernova” and “MassCompanion” in the Supernovae file

    etc.

In those cases “Mass” would be the root string, and the “1” and “2” (or “Primary” and “Secondary”), and “Supernova” and “Companion” would be suffixes added at run-time when we know which star is which.

This proposal is required if you want to have different header strings for the same COMPAS variable printed in different files.  I think this is preferable to, for example, having multiple COMPAS variables that hold the same value just so we can have different header strings – having different variables in the code that are supposed to hold the same value leaves us open to too many problems caused by variables not being kept in sync.

**Comment by ilyamandel** [comment] 2020-08-09 12:24
@reinhold-willcox , @FloorBroekgaarden , @jeffriley , @lokiysh -- this is a great discussion.  One of the identified problems (...<2ndSN) has been moved to a separate issue.  I do not see any of the remaining features described here as a bug.  There may be room for a future enhancement as Jeff identified in the last post (allowing the same variable to mean different things in different output files).  I propose closing this issue and submitting a non-urgent enhancement issues along the lines Jeff proposed.  For now, I am removing the bug label here.

**Comment by ilyamandel** [comment] 2020-08-27 06:39
Following extended discussion, the optimal solution is to improve documentation.  Opening issue #339 , and closing this one.

**Closed by ilyamandel** 2020-08-27 06:39 UTC
Labels: enhancement, urgency_low
